package e2e_test

import (
	"context"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/billhuanglofi/flowman/internal/storage"
	flowtrace "github.com/billhuanglofi/flowman/internal/trace"
)

func TestStage1HappyPath(t *testing.T) {
	// Given
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	// When
	artifacts, err := runStage1Workflow(ctx, t)

	// Then
	if err != nil {
		t.Fatalf("expected fixture-backed stage1 workflow to succeed: %v", err)
	}
	t.Logf("artifact root: %s", artifacts.outputRoot)
	t.Logf("replay request: %s", artifacts.replayRequestPath)
	t.Logf("replay flow: %s", artifacts.replayFlowPath)
	t.Logf("postman export: %s", artifacts.postmanExportPath)
	t.Logf("insomnia export: %s", artifacts.insomniaExportPath)
	if artifacts.transactionID != "TX-E2E-123" {
		t.Fatalf("expected extracted transaction id TX-E2E-123, got %q", artifacts.transactionID)
	}
	if artifacts.journey.TransactionID != artifacts.transactionID || len(artifacts.journey.Rows) != 3 {
		t.Fatalf("expected traced journey rows for transaction %q, got %#v", artifacts.transactionID, artifacts.journey)
	}
	if artifacts.journey.Rows[2].Service != "ledger" || artifacts.journey.Rows[2].DisplayLabel != flowtrace.DisplayLabelStuck {
		t.Fatalf("expected latest non-terminal PROCESS_STATE row to be highlighted, got %#v", artifacts.journey.Rows[2])
	}
	if artifacts.importedReplay.Name != "replay-TX-E2E-123" || artifacts.importedReplay.Method != "POST" {
		t.Fatalf("expected Safestore replay import to default to POST replay request, got %#v", artifacts.importedReplay)
	}
	if len(artifacts.importedReplay.ImportWarnings) == 0 {
		t.Fatalf("expected Safestore replay import to preserve secret-handling warnings, got %#v", artifacts.importedReplay)
	}
	assertHeaderEnvReference(t, artifacts.importedReplay.Headers, "Authorization", "FLOWMAN_IMPORTED_TX_E2E_123_AUTHORIZATION")
	assertHeaderEnvReference(t, artifacts.importedReplay.Headers, "X-API-Key", "FLOWMAN_IMPORTED_TX_E2E_123_X_API_KEY")
	if !strings.Contains(artifacts.generatedCurl, "Generated by Flowman. Do not edit; edit canonical YAML instead.") {
		t.Fatalf("expected generated cURL projection marker, got %s", artifacts.generatedCurl)
	}
	if !strings.Contains(artifacts.generatedHTTP, "Generated by Flowman. Do not edit; edit canonical YAML instead.") {
		t.Fatalf("expected generated HTTP projection marker, got %s", artifacts.generatedHTTP)
	}
	if artifacts.postmanImport.ImportedCount != 1 || artifacts.insomniaImport.ImportedCount != 1 {
		t.Fatalf("expected supported Postman and Insomnia fixtures to import one request each, got postman=%#v insomnia=%#v", artifacts.postmanImport, artifacts.insomniaImport)
	}
	if len(artifacts.postmanImport.Warnings) != 0 || len(artifacts.insomniaImport.Warnings) != 0 {
		t.Fatalf("expected supported subset imports without warnings, got postman=%#v insomnia=%#v", artifacts.postmanImport.Warnings, artifacts.insomniaImport.Warnings)
	}
	if artifacts.postmanExport.ExportedCount != 1 || artifacts.insomniaExport.ExportedCount != 1 {
		t.Fatalf("expected workspace export count 1, got postman=%#v insomnia=%#v", artifacts.postmanExport, artifacts.insomniaExport)
	}
	if len(artifacts.postmanReimport.RequestPaths) != 1 || len(artifacts.insomniaReimport.RequestPaths) != 1 {
		t.Fatalf("expected exported subset to re-import exactly one request, got postman=%#v insomnia=%#v", artifacts.postmanReimport, artifacts.insomniaReimport)
	}
	if _, err := storage.LoadRequest(artifacts.postmanReimport.RequestPaths[0]); err != nil {
		t.Fatalf("expected re-imported postman request to load: %v", err)
	}
	if _, err := storage.LoadRequest(artifacts.insomniaReimport.RequestPaths[0]); err != nil {
		t.Fatalf("expected re-imported insomnia request to load: %v", err)
	}
}

func TestNoSecretValuesInOutputs(t *testing.T) {
	// Given
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	// When
	artifacts, err := runStage1Workflow(ctx, t)

	// Then
	if err != nil {
		t.Fatalf("expected fixture-backed stage1 workflow to succeed: %v", err)
	}
	assertNoSecretValue(t, artifacts.generatedCurl)
	assertNoSecretValue(t, artifacts.generatedHTTP)
	assertNoSecretValue(t, artifacts.postmanExportContent)
	assertNoSecretValue(t, artifacts.insomniaExportContent)
	assertNoRawBearerExamples(t, mustReadFixture(t, "postman_supported_collection.json"))
	assertNoRawBearerExamples(t, mustReadFixture(t, "insomnia_supported_workspace.json"))
	assertNoRawBearerExamples(t, mustReadFixture(t, "postman_unsupported_collection.json"))
	for path, content := range artifacts.textArtifacts {
		if !strings.Contains(path, filepath.Join("postman-import", "requests")) && !strings.Contains(path, filepath.Join("insomnia-import", "requests")) {
			assertNoSecretValue(t, content)
			continue
		}
		assertNoSecretValue(t, content)
		if !strings.Contains(content, "env:") {
			t.Fatalf("expected imported canonical artifact %s to keep env references instead of secret values, got %s", path, content)
		}
	}
	if got := artifacts.runnerDisplayHeaders.Get("Set-Cookie"); got != "[REDACTED]" {
		t.Fatalf("expected response display headers to redact Set-Cookie, got %q", got)
	}
	if got := artifacts.runnerDisplayHeaders.Get("X-Transaction-ID"); got != "TX-E2E-123" {
		t.Fatalf("expected non-sensitive response header to remain visible, got %q", got)
	}
}
