package storage

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/billhuanglofi/flowman/internal/model"
	"gopkg.in/yaml.v3"
)

var ErrGeneratedProjection = errors.New("storage: generated projection is not canonical source")

var ErrInvalidCanonicalYAML = errors.New("storage: invalid canonical yaml")

var generatedProjectionMarkers = []string{
	"Generated by Flowman. Do not edit",
	"DO NOT EDIT; edit canonical YAML instead",
	"flowman_generated:",
	"generated_by: Flowman",
}

func LoadWorkspace(root string) (model.Workspace, error) {
	project, err := LoadProject(filepath.Join(root, "flowman.yaml"))
	if err != nil {
		return model.Workspace{}, err
	}
	environments, err := loadProjectEnvironments(root, project.Environments)
	if err != nil {
		return model.Workspace{}, err
	}
	requests, err := loadProjectRequests(root, project.Requests)
	if err != nil {
		return model.Workspace{}, err
	}
	flows, err := loadProjectFlows(root, project.Flows)
	if err != nil {
		return model.Workspace{}, err
	}
	return model.Workspace{Project: project, Environments: environments, Requests: requests, Flows: flows}, nil
}

func LoadProject(path string) (model.Project, error) {
	return loadYAML[model.Project](path)
}

func LoadEnvironment(path string) (model.Environment, error) {
	return loadYAML[model.Environment](path)
}

func LoadRequest(path string) (model.Request, error) {
	return loadYAML[model.Request](path)
}

func LoadFlow(path string) (model.Flow, error) {
	return loadYAML[model.Flow](path)
}

func MarshalCanonical(value any) ([]byte, error) {
	out, err := yaml.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("marshal canonical yaml: %w", err)
	}
	return out, nil
}

func WriteCanonical(path string, value any) error {
	out, err := MarshalCanonical(value)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create parent directory for %s: %w", path, err)
	}

	// Use atomic write-rename to prevent corruption from concurrent writes
	// Write to temporary file first, then atomically rename
	tmpPath := path + ".tmp." + fmt.Sprintf("%d", os.Getpid())
	if err := os.WriteFile(tmpPath, out, 0o644); err != nil {
		return fmt.Errorf("write temporary yaml %s: %w", tmpPath, err)
	}

	// Atomic rename - if this fails, the original file is unchanged
	if err := os.Rename(tmpPath, path); err != nil {
		os.Remove(tmpPath) // Clean up temp file on failure
		return fmt.Errorf("write canonical yaml %s: %w", path, err)
	}

	return nil
}

func loadYAML[T any](path string) (T, error) {
	var value T
	data, err := os.ReadFile(path)
	if err != nil {
		return value, fmt.Errorf("read canonical yaml %s: %w", path, err)
	}
	if hasGeneratedProjectionMarker(data) {
		return value, fmt.Errorf("%s: %w", path, ErrGeneratedProjection)
	}
	decoder := yaml.NewDecoder(bytes.NewReader(data))
	decoder.KnownFields(true)
	if err := decoder.Decode(&value); err != nil {
		return value, fmt.Errorf("decode canonical yaml %s: %w", path, err)
	}
	if err := validateCanonical(path, value); err != nil {
		return value, err
	}
	return value, nil
}

func hasGeneratedProjectionMarker(data []byte) bool {
	content := string(data)
	for _, marker := range generatedProjectionMarkers {
		if strings.Contains(content, marker) {
			return true
		}
	}
	return false
}

func loadProjectEnvironments(root string, paths []string) ([]model.Environment, error) {
	environments := make([]model.Environment, 0, len(paths))
	for _, relativePath := range paths {
		environment, err := LoadEnvironment(filepath.Join(root, relativePath))
		if err != nil {
			return nil, err
		}
		environments = append(environments, environment)
	}
	return environments, nil
}

func loadProjectRequests(root string, paths []string) ([]model.Request, error) {
	requests := make([]model.Request, 0, len(paths))
	for _, relativePath := range paths {
		request, err := LoadRequest(filepath.Join(root, relativePath))
		if err != nil {
			return nil, err
		}
		requests = append(requests, request)
	}
	return requests, nil
}

func loadProjectFlows(root string, paths []string) ([]model.Flow, error) {
	flows := make([]model.Flow, 0, len(paths))
	for _, relativePath := range paths {
		flow, err := LoadFlow(filepath.Join(root, relativePath))
		if err != nil {
			return nil, err
		}
		flows = append(flows, flow)
	}
	return flows, nil
}
