package storage_test

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/billhuanglofi/flowman/internal/storage"
)

func Test_CanonicalYAML_parses_fixture_tree(t *testing.T) {
	// Given
	root := filepath.Join("..", "..", "testdata", "flowman")

	// When
	workspace, err := storage.LoadWorkspace(root)

	// Then
	if err != nil {
		t.Fatalf("expected fixture tree to parse: %v", err)
	}
	if workspace.Project.Name != "flowman-example" {
		t.Fatalf("expected project name flowman-example, got %q", workspace.Project.Name)
	}
	if len(workspace.Environments) != 2 {
		t.Fatalf("expected two environments, got %d", len(workspace.Environments))
	}
	uat := workspace.Environments[0]
	if uat.Name != "uat" || uat.BaseURL != "https://uat.api.example.test" {
		t.Fatalf("expected uat example base url, got %#v", uat)
	}
	if uat.Oracle.DSNEnv != "FLOWMAN_UAT_ORACLE_DSN" || uat.Oracle.PasswordEnv != "FLOWMAN_UAT_ORACLE_PASSWORD" {
		t.Fatalf("expected oracle env-var names only, got %#v", uat.Oracle)
	}
	if uat.Trace.TransactionID.Header != "X-Transaction-ID" || uat.Trace.PollInterval.Duration() != 2*time.Second || uat.Trace.Timeout.Duration() != 30*time.Second {
		t.Fatalf("expected trace extraction and timing config, got %#v", uat.Trace)
	}
	if len(workspace.Requests) != 1 {
		t.Fatalf("expected one request, got %d", len(workspace.Requests))
	}
	request := workspace.Requests[0]
	if request.Method != "POST" || request.Endpoint != "payments" || request.Path != "/v1/payments" {
		t.Fatalf("expected canonical payment request routing fields, got %#v", request)
	}
	if len(request.Query) != 2 || request.Query[0].Name != "dry_run" || request.Query[0].Value != "false" {
		t.Fatalf("expected ordered request query params, got %#v", request.Query)
	}
	if request.Body.Mode != "json" || !strings.Contains(request.Body.Raw, "amount") {
		t.Fatalf("expected raw json body fixture, got %#v", request.Body)
	}
	if len(workspace.Flows) != 1 {
		t.Fatalf("expected one flow, got %d", len(workspace.Flows))
	}
	flow := workspace.Flows[0]
	if len(flow.Steps) != 2 || flow.Steps[0].Request != "requests/payment/create.request.yaml" {
		t.Fatalf("expected ordered flow steps, got %#v", flow.Steps)
	}
	if len(flow.ImportWarnings) != 1 || flow.ImportWarnings[0].Code != "postman-script-unsupported" {
		t.Fatalf("expected import warning model, got %#v", flow.ImportWarnings)
	}
}

func Test_StableYAMLOrdering_repeated_writes_match(t *testing.T) {
	// Given
	root := filepath.Join("..", "..", "testdata", "flowman")
	requestPath := filepath.Join(root, "requests", "payment", "create.request.yaml")
	request, err := storage.LoadRequest(requestPath)
	if err != nil {
		t.Fatalf("expected request fixture to parse: %v", err)
	}
	tmp := t.TempDir()
	firstPath := filepath.Join(tmp, "first.yaml")
	secondPath := filepath.Join(tmp, "second.yaml")

	// When
	first, err := storage.MarshalCanonical(request)
	if err != nil {
		t.Fatalf("expected first marshal to succeed: %v", err)
	}
	second, err := storage.MarshalCanonical(request)
	if err != nil {
		t.Fatalf("expected second marshal to succeed: %v", err)
	}
	if err := storage.WriteCanonical(firstPath, request); err != nil {
		t.Fatalf("expected first write to succeed: %v", err)
	}
	if err := storage.WriteCanonical(secondPath, request); err != nil {
		t.Fatalf("expected second write to succeed: %v", err)
	}
	firstFile, err := os.ReadFile(firstPath)
	if err != nil {
		t.Fatalf("expected first file read to succeed: %v", err)
	}
	secondFile, err := os.ReadFile(secondPath)
	if err != nil {
		t.Fatalf("expected second file read to succeed: %v", err)
	}

	// Then
	if string(first) != string(second) || string(firstFile) != string(secondFile) || string(first) != string(firstFile) {
		t.Fatalf("expected stable repeated YAML output")
	}
	fieldOrder := []string{"version:", "name:", "method:", "endpoint:", "path:", "query:", "headers:", "body:", "trace:", "import_warnings:"}
	lastIndex := -1
	output := string(first)
	for _, field := range fieldOrder {
		index := strings.Index(output, field)
		if index <= lastIndex {
			t.Fatalf("expected %q after previous canonical field in:\n%s", field, output)
		}
		lastIndex = index
	}
}

func Test_CanonicalYAML_rejects_generated_projection_marker(t *testing.T) {
	// Given
	tmp := t.TempDir()
	path := filepath.Join(tmp, "generated.request.yaml")
	content := "# Generated by Flowman. Do not edit; edit canonical YAML instead.\nversion: v1\nname: generated\nmethod: GET\nurl: https://api.example.test/status\n"
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("expected fixture write to succeed: %v", err)
	}

	// When
	_, err := storage.LoadRequest(path)

	// Then
	if !errors.Is(err, storage.ErrGeneratedProjection) {
		t.Fatalf("expected generated projection error, got %v", err)
	}
}

func Test_CanonicalYAML_rejects_unknown_fields(t *testing.T) {
	// Given
	tmp := t.TempDir()
	path := filepath.Join(tmp, "unknown-field.request.yaml")
	content := "version: v1\nname: unknown field\nmethod: GET\nurl: https://api.example.test/status\nscript: pm.test('unsupported')\n"
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("expected fixture write to succeed: %v", err)
	}

	// When
	_, err := storage.LoadRequest(path)

	// Then
	if err == nil {
		t.Fatal("expected unknown field error")
	}
	if !strings.Contains(err.Error(), "unknown-field.request.yaml") || !strings.Contains(err.Error(), "script") {
		t.Fatalf("expected actionable path and field error, got %v", err)
	}
}

func Test_CanonicalYAML_rejects_malformed_yaml(t *testing.T) {
	// Given
	tmp := t.TempDir()
	path := filepath.Join(tmp, "malformed.request.yaml")
	content := "version: v1\nname: malformed\nmethod: GET\nheaders:\n  - name: X-Test\n    value: [unterminated\n"
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("expected fixture write to succeed: %v", err)
	}

	// When
	_, err := storage.LoadRequest(path)

	// Then
	if err == nil {
		t.Fatal("expected malformed YAML error")
	}
	if !strings.Contains(err.Error(), "malformed.request.yaml") || !strings.Contains(err.Error(), "decode canonical yaml") {
		t.Fatalf("expected actionable decode path error, got %v", err)
	}
}

func Test_CanonicalYAML_rejects_missing_required_fields(t *testing.T) {
	// Given
	tmp := t.TempDir()
	path := filepath.Join(tmp, "missing-method.request.yaml")
	content := "version: v1\nname: missing method\nurl: https://api.example.test/status\n"
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("expected fixture write to succeed: %v", err)
	}

	// When
	_, err := storage.LoadRequest(path)

	// Then
	if err == nil {
		t.Fatal("expected missing required field error")
	}
	if !strings.Contains(err.Error(), "missing-method.request.yaml") || !strings.Contains(err.Error(), "method") {
		t.Fatalf("expected actionable missing method error, got %v", err)
	}
}
