package cli

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/billhuanglofi/flowman/internal/model"
	"github.com/billhuanglofi/flowman/internal/storage"
)

func Test_GenerateCurlCommand_writes_projection_for_fixture_request(t *testing.T) {
	// Given
	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	requestPath := filepath.Join("..", "..", "testdata", "flowman", "requests", "payment", "create.request.yaml")
	outputPath := filepath.Join(t.TempDir(), "task-9-curl.sh")

	// When
	err := Execute(ctx, []string{"generate", "curl", requestPath, "--env", "uat", "--out", outputPath}, stdout, stderr)

	// Then
	if err != nil {
		t.Fatalf("expected generate curl command to succeed: %v", err)
	}
	content, readErr := os.ReadFile(outputPath)
	if readErr != nil {
		t.Fatalf("expected generated curl projection to be readable: %v", readErr)
	}
	output := string(content)
	if !strings.Contains(output, "Generated by Flowman. Do not edit; edit canonical YAML instead.") {
		t.Fatalf("expected do-not-edit marker in generated curl output:\n%s", output)
	}
	if !strings.Contains(output, "https://uat.api.example.test/payments/v1/payments?dry_run=false&source=flowman-fixture") {
		t.Fatalf("expected resolved fixture URL in generated curl output:\n%s", output)
	}
	if !strings.Contains(stdout.String(), "generated curl projection at "+outputPath) {
		t.Fatalf("expected success message with output path, got %q", stdout.String())
	}
	if stderr.Len() != 0 {
		t.Fatalf("expected empty stderr, got %q", stderr.String())
	}
	if strings.Contains(output, "Bearer ") {
		t.Fatalf("expected no raw secrets in generated curl output:\n%s", output)
	}
}

func Test_GenerateHTTPCommand_writes_projection_for_fixture_request(t *testing.T) {
	// Given
	stdout := &bytes.Buffer{}
	stderr := &bytes.Buffer{}
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	requestPath := writeProjectionWorkspaceFixture(t)
	outputPath := filepath.Join(t.TempDir(), "task-9.http")

	// When
	err := Execute(ctx, []string{"generate", "http", requestPath, "--env", "uat", "--out", outputPath}, stdout, stderr)

	// Then
	if err != nil {
		t.Fatalf("expected generate http command to succeed: %v", err)
	}
	content, readErr := os.ReadFile(outputPath)
	if readErr != nil {
		t.Fatalf("expected generated http projection to be readable: %v", readErr)
	}
	output := string(content)
	if !strings.Contains(output, "Authorization: {{$processEnv FLOWMAN_TEST_AUTH}}") {
		t.Fatalf("expected env reference in generated http output:\n%s", output)
	}
	if !strings.Contains(stdout.String(), "generated http projection at "+outputPath) {
		t.Fatalf("expected success message with output path, got %q", stdout.String())
	}
	if stderr.Len() != 0 {
		t.Fatalf("expected empty stderr, got %q", stderr.String())
	}
	if strings.Contains(output, "Bearer ") {
		t.Fatalf("expected no raw secrets in generated http output:\n%s", output)
	}
}

func writeProjectionWorkspaceFixture(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	project := model.Project{
		Version:      "v1",
		Name:         "fixture",
		DefaultEnv:   "uat",
		Environments: []string{"envs/uat.yaml"},
		Requests:     []string{"requests/payment/create.request.yaml"},
	}
	environment := model.Environment{
		Version: "v1",
		Name:    "uat",
		BaseURL: "https://uat.api.example.test",
		Endpoints: []model.EndpointAlias{{
			Name: "payments",
			Path: "/payments",
		}},
		Oracle: model.OracleDatabase{
			DSNEnv:      "FLOWMAN_UAT_ORACLE_DSN",
			UserEnv:     "FLOWMAN_UAT_ORACLE_USER",
			PasswordEnv: "FLOWMAN_UAT_ORACLE_PASSWORD",
		},
		Trace: model.TraceConfig{
			TransactionID: model.TransactionIDExtraction{Header: "X-Transaction-ID"},
			PollInterval:  model.NewDuration(2 * time.Second),
			Timeout:       model.NewDuration(30 * time.Second),
		},
	}
	request := model.Request{
		Version:  "v1",
		Name:     "create payment",
		Method:   "POST",
		Endpoint: "payments",
		Path:     "/v1/payments",
		Headers: []model.Header{
			{Name: "Authorization", Env: "FLOWMAN_TEST_AUTH"},
			{Name: "Content-Type", Value: "application/json"},
		},
		Body: model.RequestBody{Mode: "json", Raw: `{"amount":"12.34"}`},
	}
	if err := storage.WriteCanonical(filepath.Join(root, "flowman.yaml"), project); err != nil {
		t.Fatalf("expected project fixture write to succeed: %v", err)
	}
	if err := storage.WriteCanonical(filepath.Join(root, "envs", "uat.yaml"), environment); err != nil {
		t.Fatalf("expected environment fixture write to succeed: %v", err)
	}
	requestPath := filepath.Join(root, "requests", "payment", "create.request.yaml")
	if err := storage.WriteCanonical(requestPath, request); err != nil {
		t.Fatalf("expected request fixture write to succeed: %v", err)
	}
	return requestPath
}
