package generate

import (
	"errors"

	"github.com/billhuanglofi/flowman/internal/model"
)

const DoNotEditMarker = "Generated by Flowman. Do not edit; edit canonical YAML instead."

var ErrRawSensitiveHeader = errors.New("generate: raw sensitive header value")

var ErrCannotResolveRequestURL = errors.New("generate: cannot resolve request URL")

type Options struct {
	Environment                 model.Environment
	UnsafeAllowSensitiveHeaders bool
}

type projection struct {
	environmentName string
	method          string
	url             string
	headers         []string
	httpHeaders     []string
	body            string
}

type renderedHeader struct {
	name      string
	curlValue string
	httpValue string
	sortKey   string
}
